# Generated by Django 3.2.12 on 2022-04-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220416_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='create_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='update_at',
        ),
    ]
